### ISSUE TITLE
Vanematel Single Choice Set'idel on Retry ja Show solution nuppude tõlked vahetuses

### ISSUE THREAD

**Issue by sanderaido** [Oppevara/oppevara#104]
Näide: https://vara.e-koolikott.ee/node/2806 (slaid 5)

Viga on H5P poolt juba parandatud, uued materjalid peaks kõik õigetpidi tõlgetega tulema, kuid vanadele materjalidele ei rakendu. Peab masstõlkimise käigus need üle käima.

**Comment by pjotrsavitski** [comment]
Should have been fixed by the translation patcher script. Linked material is working just fine.
