### ISSUE TITLE
Tekstistiilide rippmenüü "väreleb" avanemisel

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#105]
https://drive.google.com/file/d/1c-8Dzls9PkVcI-5hgRE9sBzEzLQy06FH/view

Windows+Chrome. Ei esine Mac OS X + Chrome/FF/Safari.

**Comment by pjotrsavitski** [comment]
Pole suutnud vastavat käitumist tekitada. Tundub olevat üks haruldane nähtus mida ei saa kahjusk parandada.
