### ISSUE TITLE
Teadmiste kontroll (koodnimi "Kahoot")

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#106]
Kõikide materjalide juurest on leitav moodul "Teadmiste kontroll".

![screen shot 2018-08-09 at 14 14 55](https://user-images.githubusercontent.com/380007/43896146-79974ea8-9be0-11e8-81c7-319e016adf14.png)

**Õpetaja:**

Uue teadmiste kontrolli alustamiseks valib õpetaja materjali ning klikkab nupul "Loo". Seejärel täpsustab õpetaja e-posti aadressi (kellele saadetakse õpilaste tulemused), kontrolli kehtivuse aeg (h). Nupp "Genereeri kood" loob 6-kohalise koodi, mille abil õpilased saavad teadmiste kontrolliga liituda.

![screen shot 2018-08-09 at 14 15 23](https://user-images.githubusercontent.com/380007/43896182-93f9ae6c-9be0-11e8-9127-fc72c4709b1f.png)

**Õpilane:**

Teadmiste kontrolli tegemiseks avab õpilane õpetaja poolt viidatud materjali ning klikkab nupul "Liitu". Seejärel sisestab õpetaja poolt jagatud 6-kohalise koodi ning alustab kontrolli. Ajaline piir on õpilasel töö tegemise ajal ekraanil näha.

![screen shot 2018-08-09 at 14 15 11](https://user-images.githubusercontent.com/380007/43896151-7f0df094-9be0-11e8-92bf-b1f0b1033687.png)

![screen shot 2018-08-09 at 14 15 18](https://user-images.githubusercontent.com/380007/43896174-8f11a7ec-9be0-11e8-9e60-32096ab7035d.png)

**Comment by pjotrsavitski** [comment]
Kahooti loomisel peaks sama pealkirja sisestada, hiljem näidatakse vastavat pealkirja ka mängijale.

**Comment by tammets** [comment]
Mängu alustamisel saadetakse õpetajale meil lingiga, kust avanevad õpilaste tulemused (ka mängu ajal tulemuste vaatamiseks). Link on aktiivne 36 tundi peale mängu lõppu. Mängu lõppemisel saadetakse tulemused õpetaja e-posti peale.

**Comment by pjotrsavitski** [comment]
Funktsionaalsuse ametlik nimi on **challenge**

**Comment by tammets** [comment]
Klikates nupul "Lõpeta", informeeritakse kasutajat teatega:

`Kilkatas nupul "Lõpeta", loetakse Teadmistekontroll lõppenuks. Kui sa ei ole kõiki ülesandeid eelnevalt lõpetanud, ei saadeta Sinu tulemusi õpetajale.`

**Comment by tammets** [comment]
+ lisada õpilasele, kes on kontrolli alustanud, kuvatakse teksti:

> Teadmistekontrolli vastused edastatakse automaatselt õpetajale peale seda, kui Sa oled vastanud kõigile küsimustele
