### ISSUE TITLE
GeoGebra veateated, show match

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#110]
Materjalis https://vara.e-koolikott.ee/node/5157 annavad kõik kolm GeoGebrat veateadet kui klikata Show Match valikut. 

![screen shot 2018-08-17 at 11 54 38](https://user-images.githubusercontent.com/380007/44257355-6c034780-a214-11e8-8ce6-cceefc2bab2f.png)

![screen shot 2018-08-17 at 11 54 24](https://user-images.githubusercontent.com/380007/44257356-6c034780-a214-11e8-9cb8-e8ab866cf144.png)

![screen shot 2018-08-17 at 11 54 16](https://user-images.githubusercontent.com/380007/44257357-6c034780-a214-11e8-9dc3-001c64afb028.png)

**Comment by pjotrsavitski** [comment]
Safari pole ikka korda saanud. Chrome ja Firefox tundusid toimivat.

**Comment by pjotrsavitski** [comment]
Safari on ainus mis käitub kummaliselt. Pole suutnud aru saada mis võib viga olla.

**Comment by tammets** [comment]
Pilet lahti, uurib uuesti käitumist Safaris (12).

**Comment by tammets** [comment]
Lisaks (kõigis brauserites):

https://e-koolikott.ee/portfolio?id=18826&chapterName=7_1__Ruumiliste_kujundite_loik#chapter-1
https://e-koolikott.ee/portfolio?id=18769&chapterName=3_1__Prisma__Pustprisma_taispi#chapter-1

**Comment by pjotrsavitski** [comment]
This one provides the fix: https://github.com/Oppevara/H5P.Geogebra/commit/596d7551b71bd70a14e6bc4ec77063b530857ea2

**Comment by pjotrsavitski** [comment]
Use this thread as a source in case it is ever needed to allow floating point (positive or negative) numbers as and attribute value for the inputs:
https://stackoverflow.com/questions/10256061/regular-expression-for-finding-decimal-float-numbers
