### ISSUE TITLE
Materjali sisu ei kuvata peale salvestamist

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#111]
Seotud #96 

https://vara.e-koolikott.ee/node/6330

![screen shot 2018-08-17 at 13 34 37](https://user-images.githubusercontent.com/380007/44262067-539a2980-a222-11e8-84df-6a66a225247a.png)

**Comment by pjotrsavitski** [comment]
See oli pigem mõne H5P enda mooduli uuendamise tagajärg. Suure tõenäosusega tekkis mingi moodulitevaheline konflikt, mille tõttu tuli JavaScript'i viga. Kui viga on tõsine ja see tekkib H5P sisu kuvamise protsessi käigus, siis ei kuvata mitte kui midagi.

Kuna materjal toimib, siis antud viga on suure tõenäosusega lahenenud.
