### ISSUE TITLE
Kõikidel linkidel tekstide sees pole target=_blank'i

### ISSUE THREAD

**Issue by sanderaido** [Oppevara/oppevara#113]
Lingid, millel pole muutmisvaates Target tääbi mindud, on target puudu ja avavad e-koolikotis sama iframe'i sees väliseid lehti. 

Lahenduseks on kas hunnik käsitööd või mingi javascript, mis kõigile linkidele h5p-text lementide sees lisaks targeti.

**Comment by pjotrsavitski** [comment]
Lahenduse leidmiseks oleks vaja mõnda kindlat näidet, millega saaks läbi katsetada.

Lahenduse loogika võiks olla: selekteeri kõik `h5p-text` klassiga konteineri sees olevad `<a>` elemendid millel on `target` atribuut puudu (kui keegi on sinna juba midagi lisanud, siis me austaks vastavat valikut). Siis lisada igale poole `target="_blank"`.

Katsetamist vajab ajahetk, millal hakatakse neid elemente otsima. H5P ei kipu teada andvat millal on ta visuaalidega lõpetanud. Üheks võimalikuks lahenduseks oleks vastava koodi korduv jooksutamine, kasutades `setInterval` funktsiooni. Näiteks:
```
setInterval(function() {
    H5P.jQuery('.h5p-text').find('a:not([target]).attr('target', '_blank');
}, 2500);
```
Ebameeldiv on selle protsessi pidev jooksutamine (hetkel koodi puhul oleks selleks 2.5 sekundit).

**Comment by tammets** [comment]
#119 katab sama probleemi.
