### ISSUE TITLE
Teadmiste kontrolli ikoon ja tekst peidus kitsamal ekraanil

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#115]
Ei kuvata viidet teadmiste kontrollile:

![screenshot 2018-09-26 at 09 48 38](https://user-images.githubusercontent.com/380007/46062137-8e707500-c171-11e8-8c4f-20d245c8dd20.png)

**Comment by pjotrsavitski** [comment]
Seda annaks lahendada võttes ära `overflow:hidden;`, kuid sel juhul liiguksid oleks vastaavt elementi järgmisel real kuvatud.

**Comment by pjotrsavitski** [comment]
Selle vastu aitaks vastav muudatus:
```
.h5p-content ul.h5p-actions {
    box-sizing: content-box;
    height: auto;
    display: flow-root;
}
```
Visuaalid on täpselt samad, kuid kui elemendid ei mahu ühele reale, näidatakse neid järgmisel. Kast on piisavalt kõrgeks venimas.
![screen shot 2018-09-27 at 16 13 04](https://user-images.githubusercontent.com/518331/46148228-45531a80-c270-11e8-9e23-df31d1b53e4d.png)
