### ISSUE TITLE
Embed vaates ei kuvata õpimärki

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#117]
![2018-12-03 05 20 16](https://user-images.githubusercontent.com/380007/49351562-b4a81900-f6bc-11e8-8ede-93fea0c53567.gif)

<img width="1220" alt="screenshot 2018-12-03 at 05 25 06" src="https://user-images.githubusercontent.com/380007/49351578-bffb4480-f6bc-11e8-9aec-815ab5ca42df.png">

**Comment by pjotrsavitski** [comment]
Notice sai parandatud, kuid sel pole õpimärki puudumisega mingit põhjust. Märk on puudu kuna vastava tulemuse eest ei antagi mingit märki.
