### ISSUE TITLE
GeoGebra

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#12]
Graafikud
Eesmärk: võrrand antakse õpilasele ette ja õpilane loeb sellest infot välja

- õpetaja annab ette võrrandi, mis sisestatakse Geogebra keskkonnas 
- Geogebra genereerib graafiku
- loodud graafik on kuvatakse ülesandena Drupalis (mitte pildina, vaid interaktiivse joonisena)
- õpilane valib õige(d) vastuse(d) vastavalt küsimusele (multiple choice tüüp näiteks)
- süsteem annab tagasiside vastuse õigsuse kohta

Näide:
Ülesande tekst: Leida antud võrrandi järgi nullkohad

<img width="281" alt="screen shot 2017-08-03 at 10 56 24" src="https://user-images.githubusercontent.com/380007/28911805-6c5eebd0-783a-11e7-8f57-075497332572.png">

Lähteülesanne-anname võrrandi, nuppude rida on olemas, õpilane paneb 1-2 punkti puhtal lehel, joonestab ringjoone, saame geogebralt küsida, kas tegi õige või vale ringjoone

_Eeldus on, et õpetaja joonistab õige lahenduse ette Geogebras ja siis Drupalis tehtud õpilase lahendust võrreldakse õpetaja omaga (teatud veamarginaaliga)_

Võrrandi süsteemide graafikuline lahendamine - võrrand on osaliselt ette antud, ilma vabaliikmete/vabaliige on nullid või kordajatega, õpilane lohistab jooned õigesse kohta, õpilane loeb välja info ja kirjutab tekstivälja

**Comment by pjotrsavitski** [comment]
Karli, ole nii kena ja viska sellele asjale pilgu peale. Kui ta on valmis ja täies mahus toimimas, siis võid piletit kinni panna.
