### ISSUE TITLE
Coulmni sees olevad pildid skaleeruvad liiga pikaks

### ISSUE THREAD

**Issue by sanderaido** [Oppevara/oppevara#123]
Coulmni sees olevad pildid võtavad oma laiuseks columni laiuse ja kõrguse proportsionaalselt laiusele. St. et portrait või muud kõrgemad pildid lähevad nii suureks, et et ei mahu korraga ekraanile ja peab kerima, pilti korraga polegi võimalik näha.

**Comment by sanderaido** [comment]
Üheks lahenduseks üritasin kasutada css override'i koos media query'ga, kuid see rikub ära vaate mobiilides.

**Comment by sanderaido** [comment]
Näidismaterjal: https://vara.e-koolikott.ee/node/1322

**Comment by sanderaido** [comment]
Viimases commitis olev fix pandud üles liivakasti, eelmise kommentaari materjal töötavana siin: https://htk.tlu.ee/oppevara-liivakast/node/96

**Comment by tammets** [comment]
iPadis, landscape-is, jääb osa pildist peitu materjali laadides sama fixiga.

**Comment by sanderaido** [comment]
Kui suur osa? Saad screenshoti panna?

**Comment by tammets** [comment]
![IMG_1647](https://user-images.githubusercontent.com/380007/54770936-240a3000-4bfc-11e9-999b-c73d0628fc57.png)

**Comment by sanderaido** [comment]
Väga huvitav, kas sul on see Drupali jalus koguaeg nähtaval ja materjali "peal"?

**Comment by tammets** [comment]
![08E79664-BE2A-4D57-A525-C0625A2AA5D6](https://user-images.githubusercontent.com/380007/54771135-8e22d500-4bfc-11e9-8596-2ac60da45816.png)

Portrees samuti.

**Comment by sanderaido** [comment]
Aa, tundub et seal kaob H5P enda frame'ist osa ära, sellepärast jääb peitu. Neid Download'i nuppe ka ei paista. Imelik...
