### ISSUE TITLE
e-koolikoti täisekraanivaade ei resize'i H5P sisu

### ISSUE THREAD

**Issue by sanderaido** [Oppevara/oppevara#124]
Näide: https://e-koolikott.ee/material?id=19241

Kui väiksel ekraanil vaadata materjali ja avada täisekraanvaade, ei tuvasta H5P kood, et akna suurus on muutunud ja sisu paigutub valesti.

Vajalik oleks e-koolikoti poolt välja saata brauseri resize event, kui täisekraani vaate laadimine on lõpetatud. Sama ka sellest vaatest väljudes.
`window.dispatchEvent(new Event('resize'));`

**Comment by pjotrsavitski** [comment]
Should be fixed on the e-koolikott side and would shortly be available within the live instance.
