### ISSUE TITLE
Materjalis olev tabel ei skaleeru kitsama ekraaniga

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#125]
https://vara.e-koolikott.ee/node/5361
https://e-koolikott.ee/portfolio?id=19415&chapterName=Reformatsioon#subchapter-1-1

<img width="777" alt="Screenshot 2019-04-04 at 19 56 20" src="https://user-images.githubusercontent.com/380007/55574091-34e69580-5714-11e9-9fb8-8adca6fcaab7.png">

**Comment by sanderaido** [comment]
See on kasutajapoolne viga, tabel on lihtsalt havasti vormindatud. Osade lahtrite sees  on omakorda teine tabel, millel on lahtrile pandud piksliline laius (ma ei tea miks, äkki sellepärast et need tabeli tulbad võrdse laiusega oleks?). Kui need sealt kõik ära võtta (3 lahtrit tegelt sellised, lillad täpid mu ekraanipildil), siis kõik skaleerub, kuigi lihtsalt tulbad pole ilusti ühelaiused. 

![Screen Shot 2019-04-04 at 19 16 18](https://user-images.githubusercontent.com/9868517/55574669-965b3400-5715-11e9-88b7-4fd651bb8f9b.png)

**Comment by sanderaido** [comment]
Tabeli lahtri väärtus 50% miskipärast ei mõju, see kustutatakse sealt salvestamisel ära.
