### ISSUE TITLE
Heli salvestamine ei toimi e-Koolikotis

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#127]
https://e-koolikott.ee/material?name=19__sajandi_klaverimuusika__as&id=17988 

<img width="534" alt="Screenshot 2019-04-12 at 11 05 10" src="https://user-images.githubusercontent.com/380007/56021752-e5efc000-5d12-11e9-8690-d1b9af3a7dc8.png">

**Comment by pjotrsavitski** [comment]
Latest version of Safari browser shows an error, Chrome does not show anything (just fails silently).

![Screenshot 2019-04-12 at 11 19 05](https://user-images.githubusercontent.com/518331/56023605-e25e3800-5d16-11e9-9882-e6c75871baca.png)

**Comment by pjotrsavitski** [comment]
Selgitust leiab [siit](https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes). Muudatus jõustus alles hiljuti, enne on näidatud hoiatavat teksti (vast konsoolis).

Parandus on lihtne. Lisada `<iframe>` elemendile `allow="microphone; midi"`. See tundub praegust juhtumit lahendavat. Kõikide võimaluste lubamiseks on `allow="*"`, kuigi see võib vähe lohakavõitu muudatus olla. Samas, veebilehitseja uurib lõppkasutaja k'est nii ehk naa järgi.
