### ISSUE TITLE
Teadmistekontrollis ülesanded lõpetades ei kuvata teadet, punktide arvu

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#129]
https://e-koolikott.ee/material?name=Isoprotsessid&id=13753

**Comment by pjotrsavitski** [comment]
Sel juhul on süüdi **Multiple Hotspot**, mille puhul ei oska **Column** sisutüüpi kood lõpetamist kindlaks teha (kuna tegemist pole sinna lubatud sisuga). Selle tõttu ei suuda ka **column** ise vastavat lõpetamise sõndmust tekitada.
