### ISSUE TITLE
Nupud materjali vaates ei toimi korrektselt

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#135]
https://vara.e-koolikott.ee/node/2966#overlay-context=node/2966

Klikates nuppudel:

![Screenshot 2019-05-20 at 11 08 36](https://user-images.githubusercontent.com/380007/58006040-c442df00-7aef-11e9-8b1c-64b55a319262.png)

**Comment by pjotrsavitski** [comment]
Tundub H5P enda sisu jam olevat. Ehk on mõne uuenduse tõttu tekkinud. Kas üle salvestamine ei aita?

**Comment by tammets** [comment]
> Tundub H5P enda sisu jam olevat. Ehk on mõne uuenduse tõttu tekkinud. Kas üle salvestamine ei aita?

Salvestamine ei aita.

**Comment by pjotrsavitski** [comment]
Viga tundub olevat liiga vanas `H5P.Question` teeki versioonis:

`/sites/default/files/h5p/libraries/H5P.Question-1.2/scripts/question.js?ver=1.2.2`

**Comment by pjotrsavitski** [comment]
In this case it seems to be the fault of [this](https://github.com/lukemuller/h5p-image-multiple-hotspot-question/) content type.

The repo seems to have the code for a newer version of it, but it has not been added to the central HUB. The repo seems to have been abandoned by the original author.

The solution that worked locally:

1. Go to library location and change the `H5P.Question` library dependency version from `1.2` to `1.4`. The library should be located at `WWWROOT/sites/default/files/h5p/libraries/H5P.ImageMultipleHotspotQuestion-1.0`
1. Check `h5p_libraries` table to determine what identifiers are for versions `1.2` and `1.4`
1. Replace identifier for version `1.2` with respective one for version `1.4`. NB! Make sure you use the correct `content_id` to only affect the correct content.

This should fix the current problem, as all seemed to work well enough.

The **meaningful** solution would be to update the library to a newer version that already has the newer versions of libraries set as dependencies.

**Comment by pjotrsavitski** [comment]
Forked the repositories and released new versions:
https://github.com/centre-for-educational-technology/h5p-image-multiple-hotspot-question
https://github.com/centre-for-educational-technology/h5p-editor-image-multiple-hotspot-question

Updated the server.

**NB! Make sure to save the content again in order for the dependencies to be fixed as the cache rebuild process did not have any effect for some reason.**
