### ISSUE TITLE
Tühja Grid Checker sisu ei saa kustutada

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#136]
Kustutamisel:

![Screenshot 2019-05-20 at 11 12 02](https://user-images.githubusercontent.com/380007/58006195-2996d000-7af0-11e9-8196-fb2d808648a5.png)

https://vara.e-koolikott.ee/node/3202#

**Comment by pjotrsavitski** [comment]
Uploaded new packages to the service.
