### ISSUE TITLE
Materjali ei kuvata peale salvestamist

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#137]
Üle salvestamine ei toimi.

https://vara.e-koolikott.ee/node/5648

**Comment by pjotrsavitski** [comment]
![Screenshot 2019-05-20 at 14 31 23](https://user-images.githubusercontent.com/518331/58018626-f9f5c100-7b0b-11e9-8483-70272cbd85dd.png)

Tundub H5P enda sisu koodi häda olevat.

**Comment by tammets** [comment]
Title sisaldas valemit, parandatud.
