### ISSUE TITLE
Geogebra "Show solution" kuvab veateadet

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#138]
![Screenshot 2019-05-20 at 11 31 50](https://user-images.githubusercontent.com/380007/58007440-f144c100-7af2-11e9-804c-c0bf46b15000.png)

https://vara.e-koolikott.ee/node/2920
https://vara.e-koolikott.ee/node/3217

**Comment by pjotrsavitski** [comment]
The solution is partial and has drawbacks (the reasoning could be found within the codebase itself in form of a comment).
