### ISSUE TITLE
Vihje-nupp ei toimi täisekraani vaates (Course presentation)

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#139]
https://e-koolikott.ee/portfolio?id=18610&chapterName=1_1__Nurga_moiste__#chapter-1

Nurga mõiste, slaid 5

**Comment by pjotrsavitski** [comment]
https://stackoverflow.com/questions/45798213/firefox-fullscreen-video-append-dom-elements

**Comment by pjotrsavitski** [comment]
Current fix would be to use `h5p-content` instead of `h5p-container` for usage with fullscreen.

```
// CUSTOM START
if ($element.hasClass('h5p-container') && $element.hasClass('h5p-standalone') && $element.hasClass('h5p-course-presentation') && $element.parent().hasClass('h5p-content')) {
  $element = $element.parent();
}
// CUSTOM END
```

The fix should be added before [this](https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L649) line in `h5p.js` file.
