### ISSUE TITLE
Course presentation, Interactive video, vastuse sisestamine raskendatud

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#140]
https://vara.e-koolikott.ee/node/5219#

![Screenshot 2019-05-29 at 14 34 50](https://user-images.githubusercontent.com/380007/58554177-ff938b00-821e-11e9-971a-349f768ba645.png)

+ video "hüppamine" (chrome):

![2019-05-29 14 36 04](https://user-images.githubusercontent.com/380007/58554264-35387400-821f-11e9-92d1-2fb2ff5e0656.gif)

**Comment by pjotrsavitski** [comment]
The issue is only present if **Interactive Video** is within a **Course Presentation**. The focus is not taken away while being a standalone content type.

The strange _jumpy_ behaviour is caused by one of our custom fixes (MathJax or something else).

**Comment by sanderaido** [comment]
Sama materjal e-koolikotis ei hüple:
https://e-koolikott.ee/material?name=Stereomeetria_ulesandeid&id=17541
