### ISSUE TITLE
GeoGebra, näita vastet vead

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#141]
https://vara.e-koolikott.ee/node/3822
https://vara.e-koolikott.ee/node/3612
https://vara.e-koolikott.ee/node/3618
https://vara.e-koolikott.ee/node/4137
https://vara.e-koolikott.ee/node/4145
https://vara.e-koolikott.ee/node/3996
https://vara.e-koolikott.ee/node/3679
https://vara.e-koolikott.ee/node/3624
https://vara.e-koolikott.ee/node/4313
https://vara.e-koolikott.ee/node/2967
https://vara.e-koolikott.ee/node/3116
https://vara.e-koolikott.ee/node/4512
https://vara.e-koolikott.ee/node/4061
https://vara.e-koolikott.ee/node/2535

**Comment by pjotrsavitski** [comment]
The only possible fix for this issue is to prevent showing both teacher and user created elements at once.

**Comment by pjotrsavitski** [comment]
Updated live instance with versio 1.1.9
