### ISSUE TITLE
Question Seti Drag&Drop valemite kuvamine

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#142]
https://vara.e-koolikott.ee/node/1013

![2019-05-29 15 06 45](https://user-images.githubusercontent.com/380007/58555921-6adf5c00-8223-11e9-842b-98e30859d788.gif)

**Comment by sanderaido** [comment]
Tegemist pole matemaatika / Mathjax'i veaga, see on tavaline tekst kus kasutatud <sup> elemente astmete jaoks, pärast mida tinymce paneb `&nbsp;` märgi, et brauser kindlasti tühiku sinna paneks enne miinusmärki. Kuna päris pikk valem, siis ära lõigatakse niikuinii.

**Comment by sanderaido** [comment]
See üksik materjal parandatud, asendades lohistatavad Latex koodiga.
