### ISSUE TITLE
Materjali sees ei kuvata lisatud pilte

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#143]
~https://vara.e-koolikott.ee/node/5771~
~https://vara.e-koolikott.ee/node/5708~

Pakina alla laadides ja uuesti üles laadides kuvatakse pilti.

**Comment by pjotrsavitski** [comment]
Materjali üle salvestamine tundub aitavat (olengi seda teinud).

Probleem ise seisneb selles, et piltidel oli mingil põhjusel küljes `#tmp` märk aadressi lõpus. [H5P.Image code](https://github.com/h5p/h5p-image/blob/master/image.js#L19) is using [H5P.getPath()](https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L684), mis tagastab faili path ning sisu identifikaatori järgi URL aadressi. Kui tegemist on aga [ajutise failiga](https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L694), siis tagastatakse [tühja väärtust](https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L709).

Mingil põhjusel on pildifailidele jäänud külge vastav ajutise faili väärtus.
