### ISSUE TITLE
Avalikus vaates materjali kuvamise probleem

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#148]
https://vara.e-koolikott.ee/node/2135

![Screenshot 2019-06-17 at 09 14 52](https://user-images.githubusercontent.com/380007/59582265-626e9880-90e0-11e9-94e2-0936cd5f1068.png)

**Comment by pjotrsavitski** [comment]
Kolmandal lehel on tekst puudu ning seda ei salvestata. Üks võimalus on uue lehe tekitamine, tekstide üle kopeerimine ning salvestamine (eelmine leht nr. 3 ära kustutada).
