### ISSUE TITLE
Lisada Visual Math editori pildi lisamise võimalus

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#15]

**Comment by tammets** [comment]
Valemi editori muuta ei saa, võib olla võimalus läbi CKEditori

**Comment by jkurvits** [comment]
Sooviks siia ribale vastavat pildi lisamise nuppu:
![pilt](https://user-images.githubusercontent.com/30894318/29204228-6d00cbea-7e7e-11e7-9f10-1f40999a354e.png)

**Comment by sanderaido** [comment]
Selleks on parem kasutada Columni tüüpi, kuhu saab lisada pildi ning valemi. Piltide lisamine läbi tekstiredaktori ei ole võimalik üheski H5P sisutüübis, nende haldamine käib alati tekstist eraldi.
