### ISSUE TITLE
Lünktekstis ei kuvata korrektselt indekseid peale lohistamist

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#152]
https://vara.e-koolikott.ee/node/769, content type: drag text

![2020-10-07 15 24 47](https://user-images.githubusercontent.com/380007/95330462-44b6db00-08b1-11eb-92bb-6002e0d365fa.gif)

**Comment by pjotrsavitski** [comment]
Sisutüübi lühendamise kood on siin:
https://github.com/h5p/h5p-drag-text/blob/master/src/scripts/draggable.js#L25

Elemendi **aria-label** väärtuseks on:
`Lohistatav SO<sub>3</sub> +&nbsp;H<sub>2</sub>O →&nbsp;H<sub>2</sub>SO<sub>4</sub>. 7 of 14 lohistatavatest objektidest. `

Sellest võib järeldada et teksti enda väärtuseks on:
`SO<sub>3</sub> +&nbsp;H<sub>2</sub>O →&nbsp;H<sub>2</sub>SO<sub>4</sub>`

Tähelepanu, teksti sees on `&nbsp;` kood, mille nimetuseks on **non-breaking space**. Seda kasutatakse siis kui oleks vaja kuvada nii mitu tühikut kui neid on, keelates veebilehitsejal neid sealt eemaldada.

Lühendaja loogika on lihtne: kui pikkus ületab kahtekümmend tähemärki, siis võtame esimesed 17 ning lisame lõppu kolm punkti. Selle tulemuseks on `SO<sub>3</sub> +&...`, mida kasutajale kuvataksegi.

Vastava koodi asendamine tühikuga võib anda veidike paremat tulemust, kuid valemit ei kuvata kunagi ideaalselt. Kood pole suuteline teksti sees olevast **HTML** sisust aru saada ning ennast kuidagi kohandada. Isegi kui seda oleks tehtud, ei saa mitte mingil viisil vastava valemi lühendamist korralikumalt ära teha, kuna vastavat viisi pole tõepoolest olemas ning selleks oleks vaja juba koodile valemite loogikat selgeks õpetada. Teatud oludes võib lühendamise loogika ka mõnda **HTML** koodi n.ö. _pooleks lõigata_.

See on pigem **HTML** koodi lubamise tagajärg.

Lahenduseks on iga konkreetse lünga puhul käitumist läbi katsetada ning vastava lünga teksti kohandada.

**Comment by pjotrsavitski** [comment]
Tundub et see sai _lahendatud_. Panen kinni.
