### ISSUE TITLE
Latexiga kirjutamise võimalus olemas ka nt Multiple Choice puhul

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#18]
Mõnel kasutajal on Latexiga kirjutamise võimalus olemas ka nt Multiple Choice tüübi puhul, teistel aga ei ole.

**Comment by tammets** [comment]
Palume täpsustada veebilehitseja nimi ja versioon.

**Comment by jkurvits** [comment]
Kas Course Presentationisse oleks võikmalik lisada Visual Math Input. Tegelikult oleks seda vaja iga objekti juurde.

**Comment by tammets** [comment]
@sanderaido täpsusta, milliste tüüpide juures on võimalik.
