### ISSUE TITLE
Kõikide sisutüüpide juures valemite kasutamise võimalus

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#19]

**Comment by sanderaido** [comment]
Lisaks lisada ka iframe ja Geogebra sisestamise võimalus.

Lihtsam juhend: https://github.com/h5p/h5p-course-presentation/issues/12

https://github.com/h5p/h5p-course-presentation/issues/25

**Comment by tammets** [comment]
@sanderaido - nimekiri sisutüüpidest, kus valemite kasutamine võimalik ja kus ei ole.

**Comment by sanderaido** [comment]
@jkurvits
Hetkel võimalik kasutada 

- Tavalises tekstiväljas (Course Presentationis ja Columnis)
- Fill in the blanks
- Single choice set
- Multiple choice (hetkel on ainult Retry nupu vajutamine vigane, kuid ka see saab hiljem parandatud (#51) , võib praegu juba kasutada)

Visual Math Inputi otseselt enam kasutama ei peagi, sellel pole mingit eelist tavalise text välja ees. Seega ei hakka selle nuppu eraldi ka course presentationisse ilmselt lisama.

Drag the words tüübile on natuke raskem seda hetkel implementeerida, mõtleme veel kas on võimalik.
