### ISSUE TITLE
Piltide suuruse reguleerimise võimalused

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#2]

**Comment by tammets** [comment]
Täpsustada, millised peavad olema reguleerimise võimalused ja miks ei täida kriteeriume H5P võimalused.

**Comment by pjotrsavitski** [comment]
Pildi suurust saab määrata nende H5P sisutüüpide juures, kus seda vaja läheb. Igal pool mujal näidatakse pilti täismõõdus (laius), sedasi toimib ta ka telefonides ja tahvlites.

**Comment by sanderaido** [comment]
Kui õigesti mäletan siis siin all mõeldi vist näiteks Column tüübis pildi suuruse muutmise lubamist. 
Probleemiks olid ruudukujulised pildid, mis olid sama kõrged kui laiad ning venitasid ennast columni laiuseks ning olid seega liiga suured, et mugavalt vaadata ning samal ajal selle pealt ülesannet lahendada vms.

Parim lahendus oleks ilmselt max-width implementeerimine, et väikematel seadmetel oleks max suuruses kuid suurel ekraanil ei läheks liiga suureks.

**Comment by pjotrsavitski** [comment]
Tavaliselt tehakse seda umbes nii: `width: 100%; height:auto`. Eks seda saab veel erinevate ekraani suuruste jaoks sättida. Samas, miks mitte kasutada teises mõõdus pilti?

**Comment by sanderaido** [comment]
Ruudukujulised oli tegelikult vist pigem joonised. Eriti hull on asi vertikaalsete joonistega ning siis kui joonis ise on väiksema resolutsiooniga, column venitab ta ikkagi nii suureks kui jaksab. Näide: http://htk.tlu.ee/oppevara-liivakast/node/47

**Comment by pjotrsavitski** [comment]
Jah, kuid sellise pildi puhul (tekstid peal) ei tule liiga väikeseks muutmine kõne alla. Siis pole võimalik sealt midagi välja lugeda.
