### ISSUE TITLE
Vimeo sisu vistutamise võimalus

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#21]

**Comment by pjotrsavitski** [comment]
Sekkega oli vist nii, et Vimeo lubab ainult PRO alt õiget aadressi saada. Või siis teha kasutajatele selgeks kust seda välja võluda saab.

**Comment by tammets** [comment]
Toimib, kui embed koodist leida üles järgmine osa:

```
<iframe src="**https://player.vimeo.com/video/228679111**" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/228679111">In This World</a> from <a href="https://vimeo.com/kellycreedon">Kelly Creedon</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

Ja see lingina iFrame Embedderisse panna.

**Comment by pjotrsavitski** [comment]
Just, kuna see ongi video aadress. Vimeo PRO annab arvatavasti midagi sarnast.

Suure tõenäosusega on tegemist tasulise versiooni müügivõttega.
