### ISSUE TITLE
Võimalus kasutada tabelit, mida õpilane saab täita või kuhu saab sõnu sisse lohistada.

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#26]

**Comment by tammets** [comment]
Täpsustada / välja töötada stsenaarium sisutüübi jaoks.

**Comment by jbome** [comment]
Tabel peaks olema selline, et õpetaja saab selle luua ja täita mõningad osad sellest. Ülejäänud jääb õpilasele täitmiseks. Ideaalis oleks see allalaetav, et saata vastus n meili teel õpetajale või siis teha sellest screenshot. Antud tabelitüüpi kasutatakse sotsiaalainetes palju, see annab võmaluse uurida asju eradi ja hiljem saab selle naljalt leida sarnasusi-erinevusi, teha järeldusi.

Näide: [siin](https://docs.google.com/document/d/17_YRnSiS-chZlJb_-nXUvs9Px3sT_Sr4RfjdvzS5L-g/edit?usp=sharing)

**Comment by tammets** [comment]
Dubleerib piletit #42
