### ISSUE TITLE
Tabel, kuhu saab lisada näiteid, või lisada tingmärke, nt + ja -

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#27]
Ülesandes on ette antud valdkond ja tunnused ning õpilane peab märkima, et kas antud tunnus on omane sellele valdkonnale või mitte.

**Comment by tammets** [comment]
Täpsustada stsenaarium sisutüübi tarvis.

**Comment by jbome** [comment]
Arvatavasti läheb siia alla mitu sisutüüpi aga

Kaks näidet: [siin](https://docs.google.com/document/d/1nFTCXkxpd7TNrpVDXj4lNtk-U0_AjHfS3R-rIU2tlaw/edit?usp=sharing)

Tegemist on märkeruutudega. Õpetaja peaks saama luua tabeli, kus täidab pealkirjad ja keskmise lahtri. Õpilane saab märkida vastuse (x) ainult kas esimesse või kolmandasse lahtrisse

Või siis on lahtreid neli vt kolmas tabel (rohkem tavaliselt ei ole, muidu läheb segaseks)

**Comment by tammets** [comment]
Dubleerib piletit #42
