### ISSUE TITLE
Userreport integreerimine

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#31]

**Comment by pjotrsavitski** [comment]
Nende enda lehel sovitatakse valida üks kahest võimalikst viisist: https://helpdesk.userreport.com/hc/en-us/articles/211058103-Drupal-Plugin

**Comment by pjotrsavitski** [comment]
Korras. Moodul tundus veidi lõpetamata olevat, lisasin koodi otse lehe sisse luues uue plokki.
