### ISSUE TITLE
Võimalik on lisada SVG formaadis pilte kõigile H5P sisutüüpidele, milles pildid sisalduvad

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#33]

**Comment by pjotrsavitski** [comment]
Meie Instance'is peaks tehtud olema. Kuna see nõudis ühe Core mooduli muutmist, siis see eeldab uuenduste sisse viimist peale igat uuendust.

Tegin ka vastava pull request'i: https://github.com/h5p/h5p-editor-php-library/pull/38

Kui seda heaks kiidetakse, siis on ta ka H5P koodibaasi sees.
