### ISSUE TITLE
Sõnade lohistamise ülesanne, esimese lünga paigutus

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#35]
Esimene lünk tekitatakse uuele reale:

![pilt](https://user-images.githubusercontent.com/380007/29248707-6577f7cc-8027-11e7-9d2c-8db812a93581.png)

**Comment by pjotrsavitski** [comment]
Selle mooduli loogika ei ole valmis **HTML** kujul sisu kuvamiseks. Kuna alguses leidub `<div>` elemente, siis lünkade parser ei ole valmis neid minema visata ning veebilehitseja lahkelt teeb **HTML** koodi **korda**.

Ehk siis `<div><div>Tore tekst *lünk1*, ja veel natuke teksti, ja uus *lünk1*.</div></div>` jagatakse mitmeks alamosaks, millisteks on `<div><div>Tore tekst `, `*lünk1*`, `, ja veel natuke teksti, ja uus `, `*lünk2*`, `.</div></div>`.

Hetkel teeme kindlaks et iga `<div>` element oleks sunnitud `display: inline;` olema. Seda juhul kui ta paikneb teatud plokki sees.

**Comment by tammets** [comment]
Lisada ka `<p>` elemendile `display: inline-block;`
