### ISSUE TITLE
Column objektidega GeoGebra + Täida lüngad kuvamise probleem

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#37]
Safari / Chrome:

![pilt-1](https://user-images.githubusercontent.com/380007/29252940-92542d04-8079-11e7-8734-f6e7c9c84b64.png)

Firefox:

![pilt](https://user-images.githubusercontent.com/380007/29252942-9fc356a4-8079-11e7-9115-914622c12401.png)

Värskeimad brauserid, nii Windows kui Mac - http://htk.tlu.ee/oppevara/node/943

**Comment by jkurvits** [comment]
Lisan veel paar rida. Kui kasutada Column-tüüpi objekti, siis osa sisust jääb "peitu". Sel juhul ei ole paista ka allalaadimise, litsentsi nuppu jne.
Autorid on lisanud viimaseks osaks teksti uuesti ja siis mõned tühjad read, siis on ok. 
Näiteid:
http://htk.tlu.ee/oppevara/node/969
http://htk.tlu.ee/oppevara/node/863

**Comment by tammets** [comment]
Viimasest kommentaarist tegin eraldi pileti - #41
