### ISSUE TITLE
Column-tüüpi objektiga jääb osa sisust "peitu"

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#41]
Kui kasutada Column-tüüpi objekti, siis osa sisust jääb "peitu". Sel juhul ei ole paista ka allalaadimise, litsentsi nuppu jne.
Autorid on lisanud viimaseks osaks teksti uuesti ja siis mõned tühjad read, siis on ok.
Näiteid:
http://htk.tlu.ee/oppevara/node/969
http://htk.tlu.ee/oppevara/node/863

**Comment by jkurvits** [comment]
Mulle tundub, et kui Columnis juba olemas Visual math, sõltumata sellest mitmendana on ta lisatud, siis läheb osa sisust peitu

**Comment by jkurvits** [comment]
Veel on selle Column tüübi ja Visual Mathi vahel selline probleem, et joondus ei ole sama. Teksti osa oleks nagu taandreaga ja Visual Math osa algab kohe vasakult. Jääb inetu. Samas nende tüüpidega on kõige parem väikest teooria osa esitada. http://htk.tlu.ee/oppevara/node/1211
