### ISSUE TITLE
Sisutüüp: märkeruudud

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#42]
Sisutüüp märkeruudud võimaldab kasutajal luua Google Form laadseid märkeruudustikke:
- Märkeruudud
- Mitme valikuga märkeruudud
- Tekstikastiga ruudustik

![screen shot 2017-08-23 at 13 53 11](https://user-images.githubusercontent.com/380007/29613070-e46f1064-880c-11e7-8164-c43483acb546.png)
![screen shot 2017-08-23 at 13 53 04](https://user-images.githubusercontent.com/380007/29613071-e4b55a24-880c-11e7-8c06-54075951dbd0.png)

Valikutega märkeruutude puhul saab õpetaja eelnevalt märkida õiged vastused:

![screen shot 2017-08-24 at 11 35 28](https://user-images.githubusercontent.com/380007/29657498-84cf43ea-88c0-11e7-9b68-ad3038c52615.png)

**Comment by jbome** [comment]
Super!

**Comment by pjotrsavitski** [comment]
Peaks peaaegu valmis olema. Enne avalikustamist vajaks ta veel mõningat läbi katsetamist.

**Comment by pjotrsavitski** [comment]
Initial version released and packaged. Check the [release page](https://github.com/Oppevara/h5p-grid-checker/releases/tag/1.0.0) for more information.
