### ISSUE TITLE
Taksonoomia märksõnade menüüs kuvatakse materjalide arvu

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#43]
<img width="1087" alt="screen shot 2017-08-25 at 08 46 04" src="https://user-images.githubusercontent.com/380007/29701051-f4fa480c-8971-11e7-93ac-2a31b1b85f76.png">

**Comment by tammets** [comment]
Hetkel olemasolev lahendus kuvab eelviimase taseme all olevate materjalide arvu. Ülevalpool kuvatav number ei ole vastavuses kõikide alammärksõnade all olevate materjalide arvuga.

**Comment by sanderaido** [comment]
Menüü genereerimise eest vastutab Drupal'i moodul [Taxonomy menu block](https://www.drupal.org/project/taxonomy_menu_block)

Hetkel agregeeritakse number ainult iga termini otsestele alamterminitele kuuluvate sisutüüpide arvu järgi. Peaks minema alati kuni puu lõpuni. 

Võib-olla on menüümooduli dev-release'is juba asja üritatud lahendada, üks commit mis vihjab sellele: http://cgit.drupalcode.org/taxonomy_menu_block/commit/?id=7c6ba71

**Comment by pjotrsavitski** [comment]
Vaatasin koodi, see on hooposki ühe iidsema versiooni oma. Nüüd on kood hoopiski teistsugune. Peab praeguses koodis välja uurima kuidas ta neid numbreid välja võlub, andmebaasis võetakse ikka iga term'i jaoks neid numbreid.
