### ISSUE TITLE
.h5p materjale ei saa Chrome'is alla laadida

### ISSUE THREAD

**Issue by sanderaido** [Oppevara/oppevara#44]
Chrome proovib hetkel sisu allalaadimise asemel seda avada.

**Comment by tammets** [comment]
https://h5p.org/node/10840

**Comment by pjotrsavitski** [comment]
This one could be better as it describes a solution that does not require changing the Apache main configuration files: https://www.drupal.org/node/417866

**Comment by pjotrsavitski** [comment]
Mõlemad lähenemised toimivad päris kenasti. Veebilehitseja cache võib veel mõnda aega korrektset toimimist takistada, kuid sinna ei saa midagi parata. Ühe kohaliku .htaccess faili lisamine tundub olevat natuke lihtsam kui terve Apache konfiguratsiooni muutmine (see ei nõua ka serveri taaskäivitamist).
