### ISSUE TITLE
Murdude ja juurte kasutamine, kuvamise vaade vigane

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#57]
http://htk.tlu.ee/oppevara/node/2316
http://htk.tlu.ee/oppevara/node/3165

**Comment by tammets** [comment]
- Integraali rajad liiga kaugel ja murd hunnikus: https://htk.tlu.ee/oppevara/node/3485
- Alates kolmandast slaidist ei kuva õigesti - https://htk.tlu.ee/oppevara/node/3010

**Comment by hazarada** [comment]
https://htk.tlu.ee/oppevara/node/3010 puhul on häda selles, et teksti stiil lõikab matemaatika süntaksi tükkideks
