### ISSUE TITLE
Uus sisutüüp: Muusika kompositsiooniõpetuse harjutused

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#61]
https://tarmoj.github.io/komp/?e=1.2.4

Kasutajal on võimalik koostada kompositsiooniõpetuse harjutusi järgmiste tüüpidena:

- Leia puuduv vältus 
- Määra helivältus 
- Kirjelda helikõrguse asukohta 
- Määra helistik 
- Lisa taktijoon

Määrates tüübi, genereeritakse õpilasele juhuslikkuse alusel vastava tüübi harjutus. Kordade arvu määrab ülesande koostaja.

![screen shot 2017-11-07 at 14 43 51](https://user-images.githubusercontent.com/380007/32496003-7b06b01e-c3d0-11e7-96e3-5d915ce5bb40.jpg)

**Comment by pjotrsavitski** [comment]
Enamasti toimib, kuid esineb mõningaid kummalisi käitumismustreid (H5P poolsed; näiteks: kohati ei laeta CSS faili).

**Comment by pjotrsavitski** [comment]
Uuendasin serverisse. Vajab katsetamist.
