### ISSUE TITLE
Sisutüüp - Rubric

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#67]
Vt. näide https://www.quickrubric.com/r#/create-a-rubric

Seda Rubric template’i kasutav õpetaja/autor lisab siis oma hindamismudeli instantsile pealkirja, muudab vajadusel veergude-ridade pealkirju, täidab tekstiga tabeli lahtrid (sõnastab suurepärase, hea ja rahuldava sooritustaseme kirjelduse iga hindamiskriteeriumi kohta). 
Valmis hindamismudelit (i.k. assessment rubric) kasutab õpilane enese hindamiseks, valides radio button loogikast lähtudes igas reas ühe variandi ning lõpuks salvestab vastused CSV-na. 

![screen shot 2017-12-04 at 12 15 45](https://user-images.githubusercontent.com/380007/33547626-548efe78-d8ed-11e7-9854-bed37ad9ab10.png)

**Comment by pjotrsavitski** [comment]
Peaks vastavalt kirjeldatule toimima.
