### ISSUE TITLE
SVG-fail üleslaadimisel > PNG

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#73]
Peale SVG-faili üleslaadimist (näiteks Columni sees Image sisutüüp) kuvatakse peale salvestamist PNG laiendiga fail, mille _croppimisel_ fail muutub "uduseks". Kas on võimalik, et kasutajale kuvatakse sama üles laetud SVG ning selle _croppimisel_ ei kuvata "udust" pilti?

**Comment by pjotrsavitski** [comment]
Ei usu et midagi taolist oleks võimalik. Peale pildi töötlemist muudetakse igat faili PNG'ks (kui ma ei eksi). SVG fail on tõepoolest XML, sellele on raske crop'i loogikat rakendada. Selle suurus on teatud väärtustega antud (tihtipeale on tegemist külgede suhtega).

**Comment by tammets** [comment]
Tundub nii. Lisaks "revert to original" ei kuva enam originaalfaili (SVG), vaid PNG-d peale muutmist. Enne muutmist kuvatakse kenasti SVG.
