### ISSUE TITLE
Diagrammi joonistamine õpilase poolt

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#8]
Sarnaselt EIS-ile.

**Comment by tammets** [comment]
Täpsemat näidet vaja

**Comment by pjotrsavitski** [comment]
Tundub iidne olevat. Ei usu et meil on plaanis sellega tegelema hakata.

**Comment by pjotrsavitski** [comment]
This one might do: https://github.com/centre-for-educational-technology/h5p-bpmn-js

If not, it will be tacked as part of Sisuloome project.
