### ISSUE TITLE
Valemite kuvamine, interactive video

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#80]
Materjal https://htk.tlu.ee/oppevara/node/4226

![screen shot 2018-03-13 at 14 19 49](https://user-images.githubusercontent.com/380007/37341532-6120641c-26ca-11e8-96f4-8834dec3a874.png)

**Comment by tammets** [comment]
Veel lisaks: https://vara.e-koolikott.ee/node/4890#

**Comment by pjotrsavitski** [comment]
This would be a more robust solution. Using `MutationObserver` to observe changes to the dialog attributes and run some kind of code (observing changes happening within the dialog would be a lot more resource consuming).

```
var targetNode = document.querySelector('.h5p-interactive-video .h5p-dialog-wrapper');
var config = { attributes: true, childList: false, subtree: false };

var callback = function(mutationsList, observer) {
  // Refresh MathJAX + add listeners button click events
  console.log(mutationsList, observer);
};

var observer = new MutationObserver(callback);
observer.observe(targetNode, config);
//observer.disconnect();
```
