### ISSUE TITLE
Veateade materjali salvestamisel (salvestamine õnnestus)

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#82]
![screen shot 2018-03-27 at 13 22 33](https://user-images.githubusercontent.com/380007/37961893-2ec9f5f2-31c2-11e8-9ab5-7d16bad52047.png)

![image](https://user-images.githubusercontent.com/380007/37961840-08753d58-31c2-11e8-8497-ee2f0b214bf7.png)

**Comment by pjotrsavitski** [comment]
Kummaline nähtus mis pole enam esinenud. Panen pileti kinni.
