### ISSUE TITLE
Fill in the blanks, ülesannet ei saa kontrollida, leht "hangub"

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#83]
https://vara.e-koolikott.ee/node/3024#overlay-context=node/4441

![image](https://user-images.githubusercontent.com/380007/37962534-178e246a-31c4-11e8-84ca-10e956e1475f.png)

![image-1](https://user-images.githubusercontent.com/380007/37962540-1c16e7f6-31c4-11e8-95e8-1f227df19c7c.png)

**Comment by pjotrsavitski** [comment]
Probleem on `H5P.Blanks` mooduli `blanks.js` failis meetodis `getxAPIDefinition`

Nimelt, süüdlaseks on `definition.correctResponsesPattern` ja selle täitmisega tegelev kood. Selle eesmärk on genereerida kõikide võimalike õigete vastuste variatsioone. Kui variatsioonide arv ulatub miljonitesse, siis võtab koodi jooksutamine liialt kaua aega.

Lahenduseks oleks vastava funktsionaalsuse välja kommenteerimine (seda igas võimalikus `H5P.Blanks` versiooni koodis.

Peab kindlaks tegema, et see ei ajaks LRS süsteemi hulluks ning too võtaks vastava statement'i vastu.

**Comment by pjotrsavitski** [comment]
Siin on üks võimalik parandus, mis eemaldab õgete vastuste variatsioonide genereerimist. xAPI stardardi järgi pole tegemist nõutud infoga, seega pole LRS'il selle vastu midagi. Muus osas jääb kõik ligikaudu samaks.

https://gist.github.com/pjotrsavitski/7e46357cd5c4012b7cd9047739ac440e
