### ISSUE TITLE
Elementide kopeerumine erinevatesse objektidesse

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#86]
Columnis "Drag and Drop" objektis lisatud elemendid kopeeritakse ilma käskluseta samas Columnis olevasse Course Presentationisse ja ühte tagapool samas Columnis olevasse Course Presentationisse.

Vt palun 7. ülesande elemendid 3. ülesande Course Presentationis ja 8. ülesande Course Presentationi 3. slaidil.

https://vara.e-koolikott.ee/node/5185

**Comment by pjotrsavitski** [comment]
We are no longer able to reproduce the issue.
