### ISSUE TITLE
Valemid ei tööta DragText ülesandes pärast lohistamist

### ISSUE THREAD

**Issue by sanderaido** [Oppevara/oppevara#87]
Tehniline: bloki lohistamisel kustutatakse eelmine objekt ning luuakse uus objekt sama sisuga, seega Mathjax vajaks uut re-renderit (peale igat drop'i). Lisaks on vaja kontrollida, et lahtrite sees töötaks vastuse kontroll ka renderdatud matemaatikaga, sest vastust kontrollitakse tegelikult latex-koodi vastu (mille mathjax keerab mathML'iks, seega ilmselt ka õiged vastused ei pruugi klappida)

**Comment by tammets** [comment]
https://vara.e-koolikott.ee/node/4646#overlay-context=node/4646
