### ISSUE TITLE
GeoGebra - materjali ei õnnestu salvestada

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#91]
Materjali muutmine ei õnnestu. Toimib, kui eemaldada materjalist GeoGebra.

![screen shot 2018-05-15 at 14 35 51](https://user-images.githubusercontent.com/380007/40054492-aeafc8d0-584d-11e8-81c9-2548f5b28364.png)

**Comment by sanderaido** [comment]
Kas võib probleem olla selles, et ma mingiaeg muutsin H5P.Geogebra 1.1'lt tagasi versioonile 1.0 (eraldi branchis). Kui seal 1.1 + KarliLibrary's olid mingid muudatused, mida ma ei suutnud 1.0'i tagasi viia (sest seal ei saa KarliLibrary't kasutada dependency tõttu), siis äkki on see parse'imise kood natuke vale selles viimases versioonis mis praegu kasutajatele saadaval on. Ma üritasin küll committe vaadata ja kogu koodi kaasa panna, aga äkki mingi loogika jäi kahe silma vahele. 

1.0.x versiooni on vaja, et see columnis edasi töötaks ja vanu uuendaks.

**Comment by tammets** [comment]
https://vara.e-koolikott.ee/node/5354
https://vara.e-koolikott.ee/node/5303
