### ISSUE TITLE
Image hotspot Question set-i sees

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#96]
Lisades Question set-i Image Hotspot-i, ei kuvata olemasolevat materjali (https://vara.e-koolikott.ee/node/5945).

Logiteated peale salvestamist ja uuesti edit-vaate avamist sama materjali puhul:

https://vara.e-koolikott.ee/h5peditor/82c0edcf27f94/12384/libraries/H5P.DragQuestion/1/11

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 funktsioonis H5peditor->getLibraryData() (rida 369 / /srv/vara/sites/all/modules/h5p/modules/h5peditor/h5peditor/h5peditor.class.php).

https://vara.e-koolikott.ee/h5peditor/82c0edcf27f94/12384/libraries/H5P.DragQuestion/1/11

Warning: file_get_contents(https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML,https://vara.e-koolikott.ee/ov_h5p/mathjax_conf.js): failed to open stream: no suitable wrapper could be found funktsioonis H5peditor->getLibraryData() (rida 369 / /srv/vara/sites/all/modules/h5p/modules/h5peditor/h5peditor/h5peditor.class.php).

**Comment by tammets** [comment]
Lisaks materjal https://vara.e-koolikott.ee/node/5953, mille sees annab veateate nii **ImageMultipleHotspotQuestion**, **CoursePresentation** kui **DragQuestion**.

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 funktsioonis H5peditor->getLibraryData() (rida 369 / /srv/vara/sites/all/modules/h5p/modules/h5peditor/h5peditor/h5peditor.class.php).

Warning: file_get_contents(https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML,https://vara.e-koolikott.ee/ov_h5p/mathjax_conf.js): failed to open stream: no suitable wrapper could be found funktsioonis H5peditor->getLibraryData() (rida 369 / /srv/vara/sites/all/modules/h5p/modules/h5peditor/h5peditor/h5peditor.class.php).

**Comment by sanderaido** [comment]
Image Hotspot ei põhine Question sisutüübil, ehk ta ei ole hinnatav sisutüüp. Seda ei saa ka ise kuidagi parandada, sest Question Set vajab kindlasti lõpetatavaid (hinnatavaid) sisutüüpe, aga tavaline ImageHotspot on lihtsalt informatiivne sisutüüp, mitte ülesanne. 

Võibolla oleks kunagi võimalik Find Hotspot'i sinna lisada, kui H5P sellele Questioni meetodeid lisaks, aga ka seda ei ole võimalik väljastpoolt kuidagi lahendada. Find Multiple Hotspot töötab praegu Question Set'i sees, aga seda sinna lisades ei saa testi lõpetada (viimasele slaidile ei teki "Lõpeta" nuppu ja ei saa tagasisidet.
