### ISSUE TITLE
Vahetada ära päise logo

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#97]
Õige logo: http://www.struktuurifondid.ee/sites/default/files/el_sotsiaalfond_horisontaalne.jpg

**Comment by pjotrsavitski** [comment]
Fail: templates/page.tpl.php

`<img src="<?php print url('el-logo/el_logo.png'); ?>" id="el-logo">`

Sedasi laetakse pilti õigest kohast, mitte liivakastist.
