### ISSUE TITLE
Kekule Reaction Columnis, ei luba valemit sisestada

### ISSUE THREAD

**Issue by tammets** [Oppevara/oppevara#99]
https://vara.e-koolikott.ee/node/366#overlay-context=

Column võimaldab lisada Reaction Exercise tüüpi osa, kuid vajutades muutmise ikoonile, ei ava võimalust midagi sisestada.

Toimib Columni väliselt.

**Comment by sanderaido** [comment]
Töötav versioon: https://vara.e-koolikott.ee/node/6414
